#!/usr/bin/env python3
"""Translate ft8_lib's constants.c tables into Rust.

Pipe the output through `cargo fmt` — this emits valid but unformatted Rust.

Mechanical, because the LDPC tables are ~1300 numbers and hand-copying them
would introduce exactly the kind of single-digit error that shows up as "some
messages don't decode" months later. The counts are asserted here and the
byte sums are printed so the Rust side can be checked independently.
"""
import re, sys, pathlib

SRC = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'ft8_lib/ft8/constants.c')
text = SRC.read_text()

def grab(name):
    """Return the flat list of integers in the initialiser for `name`.

    Brace-matched rather than regex-terminated: a lazy `.*?\n};` runs straight
    past a single-line declaration into the next table, which silently yields a
    concatenation instead of failing.
    """
    m = re.search(r'\b' + re.escape(name) + r'\b[^=]*=\s*', text)
    if not m:
        raise SystemExit(f'{name}: not found')
    i = text.index('{', m.end())
    depth, j = 0, i
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                break
        j += 1
    body = re.sub(r'//[^\n]*', '', text[i + 1:j])   # strip bit-pattern comments
    return [int(v, 0) for v in re.findall(r'0[xX][0-9a-fA-F]+|\d+', body)]

def rust_1d(name, ty, vals, per_line=12):
    rows = [', '.join(f'0x{v:02x}' if ty == 'u8' and v > 9 else str(v)
                      for v in vals[i:i + per_line])
            for i in range(0, len(vals), per_line)]
    body = ',\n    '.join(rows)
    return f'pub const {name}: [{ty}; {len(vals)}] = [\n    {body},\n];\n'

def rust_2d(name, ty, vals, cols, hex_=True):
    assert len(vals) % cols == 0, (name, len(vals), cols)
    rows = len(vals) // cols
    fmt = (lambda v: f'0x{v:02x}') if hex_ else (lambda v: str(v))
    lines = ',\n    '.join(
        '[' + ', '.join(fmt(v) for v in vals[r * cols:(r + 1) * cols]) + ']'
        for r in range(rows))
    return f'pub const {name}: [[{ty}; {cols}]; {rows}] = [\n    {lines},\n];\n'

tables = {}
for n in ['kFT8_Costas_pattern', 'kFT8_Gray_map', 'kFT4_Gray_map',
          'kFT4_XOR_sequence', 'kFT4_Costas_pattern', 'kFTX_LDPC_generator',
          'kFTX_LDPC_Nm', 'kFTX_LDPC_Mn', 'kFTX_LDPC_Num_rows']:
    tables[n] = grab(n)

# Shapes straight from constants.h — assert rather than trust the parse.
expect = {
    'kFT8_Costas_pattern': 7, 'kFT8_Gray_map': 8, 'kFT4_Gray_map': 4,
    'kFT4_XOR_sequence': 10, 'kFT4_Costas_pattern': 16,
    'kFTX_LDPC_generator': 83 * 12, 'kFTX_LDPC_Nm': 83 * 7,
    'kFTX_LDPC_Mn': 174 * 3, 'kFTX_LDPC_Num_rows': 83,
}
for n, want in expect.items():
    got = len(tables[n])
    assert got == want, f'{n}: parsed {got} values, expected {want}'

out = ['''//! LDPC / sync tables for FT8 and FT4.
//!
//! Ported from ft8_lib (MIT, © 2018 Kārlis Goba), which in turn took the LDPC
//! matrices from WSJT-X's ldpc_174_91_c_reordered_parity.f90 and bpdecode174.f90.
//!
//! GENERATED by tools/gen_constants.py — do not hand-edit. The tables are ~1300
//! numbers and a single wrong digit shows up much later as "some messages just
//! do not decode". `tests::table_checksums` pins them.
#![allow(clippy::all)]

/// FT8 symbol period (s); sets both tone spacing (6.25 Hz) and symbol rate.
pub const FT8_SYMBOL_PERIOD: f32 = 0.160;
/// FT8 slot period (s).
pub const FT8_SLOT_TIME: f32 = 15.0;
pub const FT4_SYMBOL_PERIOD: f32 = 0.048;
pub const FT4_SLOT_TIME: f32 = 7.5;

/// Data symbols.
pub const FT8_ND: usize = 58;
/// Total channel symbols (sync + data).
pub const FT8_NN: usize = 79;
pub const FT8_LENGTH_SYNC: usize = 7;
pub const FT8_NUM_SYNC: usize = 3;
pub const FT8_SYNC_OFFSET: usize = 36;

pub const FT4_ND: usize = 87;
pub const FT4_NR: usize = 2;
pub const FT4_NN: usize = 105;
pub const FT4_LENGTH_SYNC: usize = 4;
pub const FT4_NUM_SYNC: usize = 4;
pub const FT4_SYNC_OFFSET: usize = 33;

/// Bits in the encoded message (payload + LDPC parity).
pub const LDPC_N: usize = 174;
/// Payload bits, including the CRC.
pub const LDPC_K: usize = 91;
/// LDPC parity bits.
pub const LDPC_M: usize = 83;
pub const LDPC_N_BYTES: usize = (LDPC_N + 7) / 8;
pub const LDPC_K_BYTES: usize = (LDPC_K + 7) / 8;

/// CRC-14 polynomial, leading 1 implicit.
pub const CRC_POLYNOMIAL: u16 = 0x2757;
pub const CRC_WIDTH: u32 = 14;
''']

out.append(rust_1d('FT8_COSTAS_PATTERN', 'u8', tables['kFT8_Costas_pattern'], 7))
out.append(rust_2d('FT4_COSTAS_PATTERN', 'u8', tables['kFT4_Costas_pattern'], 4, hex_=False))
out.append(rust_1d('FT8_GRAY_MAP', 'u8', tables['kFT8_Gray_map'], 8))
out.append(rust_1d('FT4_GRAY_MAP', 'u8', tables['kFT4_Gray_map'], 4))
out.append(rust_1d('FT4_XOR_SEQUENCE', 'u8', tables['kFT4_XOR_sequence'], 10))
out.append('/// Parity generator matrix, bit-packed MSB first.\n')
out.append(rust_2d('LDPC_GENERATOR', 'u8', tables['kFTX_LDPC_generator'], 12))
out.append('/// Each row lists the codeword bits (1-origin) in one parity check.\n')
out.append(rust_2d('LDPC_NM', 'u8', tables['kFTX_LDPC_Nm'], 7, hex_=False))
out.append('/// Each row lists the three parity checks (1-origin) a codeword bit joins.\n')
out.append(rust_2d('LDPC_MN', 'u8', tables['kFTX_LDPC_Mn'], 3, hex_=False))
out.append('/// Live entries per row of `LDPC_NM` (rows are padded to 7).\n')
out.append(rust_1d('LDPC_NUM_ROWS', 'u8', tables['kFTX_LDPC_Num_rows'], 16))

sums = {n: sum(v) for n, v in tables.items()}
out.append('\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n')
out.append('    /// Byte sums computed from ft8_lib\'s constants.c at port time. A\n')
out.append('    /// mis-transcribed digit changes one of these; nothing else would.\n')
out.append('    #[test]\n    fn table_checksums() {\n')
for rn, cn in [('LDPC_GENERATOR', 'kFTX_LDPC_generator'), ('LDPC_NM', 'kFTX_LDPC_Nm'),
               ('LDPC_MN', 'kFTX_LDPC_Mn')]:
    out.append(f'        assert_eq!({rn}.iter().flatten().map(|&v| v as u32).sum::<u32>(), {sums[cn]});\n')
out.append(f'        assert_eq!(LDPC_NUM_ROWS.iter().map(|&v| v as u32).sum::<u32>(), {sums["kFTX_LDPC_Num_rows"]});\n')
out.append(f'        assert_eq!(FT8_COSTAS_PATTERN.iter().map(|&v| v as u32).sum::<u32>(), {sums["kFT8_Costas_pattern"]});\n')
out.append('        // Every Nm row must list exactly as many bits as Num_rows claims.\n')
out.append('        for (r, &n) in LDPC_NUM_ROWS.iter().enumerate() {\n')
out.append('            assert!(n as usize <= 7);\n')
out.append('            for c in (n as usize)..7 { assert_eq!(LDPC_NM[r][c], 0, "row {r} pad"); }\n')
out.append('            for c in 0..(n as usize) { assert!(LDPC_NM[r][c] as usize <= LDPC_N); }\n')
out.append('        }\n')
out.append('        // Mn is the transpose of Nm: each bit claims 3 checks that must claim it back.\n')
out.append('        for bit in 0..LDPC_N {\n')
out.append('            for &chk in &LDPC_MN[bit] {\n')
out.append('                if chk == 0 { continue; }\n')
out.append('                let row = &LDPC_NM[chk as usize - 1];\n')
out.append('                assert!(row.iter().any(|&b| b as usize == bit + 1),\n')
out.append('                    "bit {bit} claims check {chk}, which does not claim it back");\n')
out.append('            }\n')
out.append('        }\n')
out.append('    }\n}\n')

sys.stdout.write(''.join(out))
sys.stderr.write(f'parsed OK: {", ".join(f"{n}={len(v)}" for n, v in tables.items())}\n')
